env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - prettier
plugins:
  - prettier
parserOptions:
  ecmaVersion: 12
rules: { 'import/no-unresolved': 0, no-underscore-dangle: 0 }
overrides:
  - env:
      mocha: true
    files:
      - 'test/helpers.js'
      - '**/*.test.js'
